=== AntonPalmqvist/physically-based-api/schemas/schema-cameras.json
{
  "$schema": "http://json-schema.org/schema",
  "title": "Camera",
  "description": "Any type of camera that is being used, or simulated, in any way in CG productions (including games).",
  "type": "array",
  "items": {
    "additionalProperties": false,
    "properties": {
      "name": {
        "description": "Name of the camera.",
        "type": "string",
        "default": "Name"
      },
      "sensorSize": {
        "description": "Array of sensor sizes. First item specifies the size of a fully open gate. If needed, additional sizes can be added for cameras that crop the sensor.",
        "type": "array",
        "minItems": 1,
        "items": {
          "additionalProperties": false,
          "type": "object",
          "properties": {
            "format": {
              "description": "Specifies the sensor format.",
              "type": "string",
              "default": "Open Gate"
            },
            "size": {
              "description": "Sensor size in millimeters (WxH).",
              "type": "array",
              "items": {
                "type": "number"
              },
              "default": [36, 24],
              "minItems": 2,
              "maxItems": 2
            },
            "resolution": {
              "description": "Recording resolution measured in pixels [Width, Height]. One sensor size can have multiple recording resolutions. For still cameras, only movie recording resolutions are listed.",
              "type": "array",
              "minItems": 1,
              "items": {
                "type": "object",
                "properties": {
                  "format": {
                    "description": "Specifies the recording resolution format.",
                    "type": "string"
                  },
                  "size": {
                    "description": "Recording resolution measured in pixels [Width, Height].",
                    "type": "array",
                    "items": {
                      "type": "integer"
                    },
                    "default": [3000, 2000],
                    "minItems": 2,
                    "maxItems": 2
                  }
                }
              }
            }
          },
          "required": ["format", "size"]
        }
      },
      "category": {
        "type": "array",
        "items": {
          "enum": ["Still", "Movie", "Mobile"]
        },
        "minItems": 1,
        "maxItems": 1
      },
      "description": {
        "description": "This field should be used for disclaimers and other useful info for CG artists that may affect the way they use the values. It's totally fine to leave this empty.",
        "type": "string",
        "maxLength": 500
      },
      "sources": {
        "description": "Provide at least one source for the values. Source link to official manufacturer website is preferred.",
        "type": "array",
        "items": {
          "type": "string",
          "minLength": 1
        },
        "minItems": 1,
        "uniqueItems": true
      },
      "tags": {
        "description": "Tags",
        "type": "array",
        "items": {
          "type": "string"
        },
        "uniqueItems": true
      }
    },
    "required": ["name", "sensorSize", "category", "description", "sources"]
  }
}

=== AntonPalmqvist/physically-based-api/deploy/cameras.json
[
  {
    "name": "Arri Alexa 35",
    "sensorSize": [
      {
        "format": "4.6K 3:2 Open Gate",
        "size": [27.99, 19.22],
        "resolution": [
          {
            "format": "4.6K",
            "size": [4608, 3164]
          }
        ]
      },
      {
        "format": "4.6K 16:9",
        "size": [27.99, 15.75],
        "resolution": [
          {
            "format": "4.6K",
            "size": [4608, 2592]
          },
          {
            "format": "4K",
            "size": [4096, 2304]
          }
        ]
      },
      {
        "format": "4K 16:9",
        "size": [24.88, 14],
        "resolution": [
          {
            "format": "4K",
            "size": [4096, 2304]
          },
          {
            "format": "UHD",
            "size": [3840, 2160]
          },
          {
            "format": "2K",
            "size": [2048, 1152]
          },
          {
            "format": "HD",
            "size": [1920, 1080]
          }
        ]
      },
      {
        "format": "4K 2:1",
        "size": [24.88, 12.44],
        "resolution": [
          {
            "format": "4K",
            "size": [4096, 2048]
          }
        ]
      },
      {
        "format": "3.8K 16:9",
        "size": [23.33, 13.12],
        "resolution": [
          {
            "format": "4K",
            "size": [3840, 2160]
          }
        ]
      },
      {
        "format": "3.3K 6:5",
        "size": [20.22, 16.95],
        "resolution": [
          {
            "format": "3.3K",
            "size": [3328, 2790]
          },
          {
            "format": "4K 2.39:1 Ana 2x",
            "size": [4096, 1716]
          }
        ]
      },
      {
        "format": "3K 1:1",
        "size": [18.66, 18.66],
        "resolution": [
          {
            "format": "3K",
            "size": [3072, 3072]
          },
          {
            "format": "3.8K 2:1 Ana 2x",
            "size": [3840, 2160]
          }
        ]
      },
      {
        "format": "2.7K 8:9",
        "size": [16.66, 18.75],
        "resolution": [
          {
            "format": "UHD 16:9 Ana 2x",
            "size": [3840, 2160]
          }
        ]
      },
      {
        "format": "2K 16:9 S16",
        "size": [12.44, 7],
        "resolution": [
          {
            "format": "2K",
            "size": [2048, 1152]
          }
        ]
      }
    ],
    "category": ["Movie"],
    "description": "",
    "sources": [
      "https://www.arri.com/en/camera-systems/cameras/alexa-35",
      "https://www.arri.com/resource/blob/296424/88454a5a3dee9fe1d3fd68e75aa3411e/alexa-35-recording-format-poster-data.pdf",
      "https://www.arri.com/resource/blob/277386/a8ebd70f6105162b541bc39f4ad098b5/2022-05-arri-formatsandresolutionsoverview-4-4-data.pdf"
    ],
    "tags": [""]
  },
  {
    "name": "Arri Alexa 65",
    "sensorSize": [
      {
        "format": "Open Gate",
        "size": [54.12, 25.58],
        "resolution": [
          {
            "format": "Open Gate",
            "size": [6560, 3100]
          }
        ]
      },
      {
        "format": "5.1K 16:9",
        "size": [42.24, 23.76],
        "resolution": [
          {
            "format": "5.1K 16:9",
            "size": [5120, 2880]
          }
        ]
      },
      {
        "format": "LF Open Gate",
        "size": [36.7, 25.54],
        "resolution": [
          {
            "format": "LF Open Gate",
            "size": [4448, 3096]
          }
        ]
      },
      {
        "format": "4.3K 3:2",
        "size": [35.64, 23.76],
        "resolution": [
          {
            "format": "4.3K 3:2",
            "size": [4320, 2880]
          }
        ]
      },
      {
        "format": "4K UHD",
        "size": [31.68, 17.82],
        "resolution": [
          {
            "format": "4K UHD",
            "size": [3840, 2160]
          }
        ]
      }
    ],
    "category": ["Movie"],
    "description": "",
    "sources": [
      "https://www.arrirental.com/en/cameras/exclusive-cameras/alexa-65",
      "https://www.arri.com/resource/blob/277386/a8ebd70f6105162b541bc39f4ad098b5/2022-05-arri-formatsandresolutionsoverview-4-4-data.pdf",
      "https://en.wikipedia.org/wiki/IMAX#Film_cameras"
    ],
    "tags": ["imax"]
  },
  {
    "name": "Arri Amira",
    "sensorSize": [
      {
        "format": "4K UHD",
        "size": [26.4, 14.85],
        "resolution": [
          {
            "format": "4K UHD",
            "size": [3840, 2160]
          }
        ]
      },
      {
        "format": "3.2K",
        "size": [26.4, 14.85],
        "resolution": [
          {
            "format": "3.2K",
            "size": [3200, 1800]
          }
        ]
      },
      {
        "format": "2.8K",
        "size": [23.76, 13.37],
        "resolution": [
          {
            "format": "2.8K",
            "size": [2880, 1620]
          }
        ]
      },
      {
        "format": "2K",
        "size": [23.66, 13.3],
        "resolution": [
          {
            "format": "2K",
            "size": [2048, 1152]
          }
        ]
      },
      {
        "format": "HD",
        "size": [23.76, 13.37],
        "resolution": [
          {
            "format": "HD",
            "size": [1920, 1080]
          }
        ]
      },
      {
        "format": "S16 HD",
        "size": [13.2, 7.425],
        "resolution": [
          {
            "format": "S16 HD",
            "size": [1920, 1080]
          }
        ]
      }
    ],
    "category": ["Movie"],
    "description": "",
    "sources": [
      "https://www.arri.com/en/camera-systems/cameras/amira",
      "https://www.arri.com/resource/blob/277386/a8ebd70f6105162b541bc39f4ad098b5/2022-05-arri-formatsandresolutionsoverview-4-4-data.pdf"
    ],
    "tags": ["super 35"]
  },
  {
    "name": "Arri Alexa LF",
    "sensorSize": [
      {
        "format": "LF Open Gate 4.5K",
        "size": [36.7, 25.54],
        "resolution": [
          {
            "format": "LF Open Gate 4.5K",
            "size": [4448, 3096]
          }
        ]
      },
      {
        "format": "LF 2.39:1 4.5K",
        "size": [36.7, 15.31],
        "resolution": [
          {
            "format": "LF 2.39:1 4.5K",
            "size": [4448, 1856]
          }
        ]
      },
      {
        "format": "LF 16:9 UHD",
        "size": [31.68, 17.82],
        "resolution": [
          {
            "format": "LF 16:9 UHD",
            "size": [3840, 2160]
          }
        ]
      },
      {
        "format": "LF 16:9 2K",
        "size": [31.68, 17.82],
        "resolution": [
          {
            "format": "LF 16:9 2K",
            "size": [2048, 1152]
          }
        ]
      },
      {
        "format": "LF 16:9 HD",
        "size": [31.68, 17.82],
        "resolution": [
          {
            "format": "LF 16:9 HD",
            "size": [1920, 1080]
          }
        ]
      }
    ],
    "category": ["Movie"],
    "description": "",
    "sources": [
      "https://www.arri.com/en/camera-systems/cameras/alexa-lf",
      "https://en.wikipedia.org/wiki/IMAX#Film_cameras",
      "https://www.arri.com/resource/blob/277386/a8ebd70f6105162b541bc39f4ad098b5/2022-05-arri-formatsandresolutionsoverview-4-4-data.pdf"
    ],
    "tags": ["super 35", "imax"]
  },
  {
    "name": "Arri Alexa Mini",
    "sensorSize": [
      {
        "format": "Open Gate 3.4K",
        "size": [28.25, 18.17],
        "resolution": [
          {
            "format": "Open Gate 3.4K",
            "size": [3424, 2202]
          }
        ]
      },
      {
        "format": "4K UHD",
        "size": [26.4, 14.85],
        "resolution": [
          {
            "format": "4K UHD",
            "size": [3840, 2160]
          }
        ]
      },
      {
        "format": "3.2K",
        "size": [26.4, 14.85],
        "resolution": [
          {
            "format": "3.2K",
            "size": [3200, 1800]
          }
        ]
      },
      {
        "format": "4:3 2.8K",
        "size": [23.76, 17.82],
        "resolution": [
          {
            "format": "4:3 2.8K",
            "size": [2880, 2160]
          }
        ]
      },
      {
        "format": "2.8K",
        "size": [23.76, 13.37],
        "resolution": [
          {
            "format": "2.8K",
            "size": [2880, 1620]
          }
        ]
      },
      {
        "format": "2K",
        "size": [23.66, 13.3],
        "resolution": [
          {
            "format": "2K",
            "size": [2048, 1152]
          }
        ]
      },
      {
        "format": "2.39:1 2K Anamorphic",
        "size": [21.12, 17.7],
        "resolution": [
          {
            "format": "2.39:1 2K Anamorphic",
            "size": [2048, 858]
          }
        ]
      },
      {
        "format": "HD",
        "size": [23.76, 13.37],
        "resolution": [
          {
            "format": "HD",
            "size": [1920, 1080]
          }
        ]
      },
      {
        "format": "HD Anamorphic",
        "size": [15.84, 17.82],
        "resolution": [
          {
            "format": "HD Anamorphic",
            "size": [1920, 1080]
          }
        ]
      },
      {
        "format": "S16 HD",
        "size": [13.2, 7.425],
        "resolution": [
          {
            "format": "S16 HD",
            "size": [1920, 1080]
          }
        ]
      }
    ],
    "category": ["Movie"],
    "description": "",
    "sources": [
      "https://www.arri.com/en/camera-systems/cameras/legacy-camera-systems/alexa-mini",
      "https://www.arri.com/resource/blob/277386/a8ebd70f6105162b541bc39f4ad098b5/2022-05-arri-formatsandresolutionsoverview-4-4-data.pdf"
    ],
    "tags": ["super 35"]
  },
  {
    "name": "Arri Alexa Mini LF",
    "sensorSize": [
      {
        "format": "4.5K LF 3:2 Open Gate",
        "size": [36.7, 25.54],
        "resolution": [
          {
            "format": "4.5K LF 3:2 Open Gate 4.5K",
