=== AntonPalmqvist/physically-based-api/schemas/schema-materials.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Material",
  "description": "PBR material using the Autodesk Standard Surface naming conventions: https://autodesk.github.io/standard-surface/",
  "type": "array",
  "items": {
    "additionalProperties": false,
    "properties": {
      "name": {
        "description": "Name of the material.",
        "type": "string",
        "default": "Name"
      },
      "color": {
        "description": "Specifies the diffuse or metallic reflectance color, or in the case of a transparent material, transmission color. RGB triplet (vec3) in linear decimal format in rec709 primaries.",
        "type": "array",
        "items": {
          "type": "number"
        },
        "default": [0.5, 0.5, 0.5],
        "minItems": 3,
        "maxItems": 3
      },
      "metalness": {
        "description": "Specifies how metallic the material appears (dials the shading model from pure dielectric to pure metal).",
        "type": "number",
        "default": 0
      },
      "specularColor": {
        "description": "Color of the specular reflection for metals, specified in the \"Gulbrandsen edge tint\" format. Calculated from spectral data using script from https://github.com/natyh/material-params",
        "type": "array",
        "items": {
          "type": "number"
        },
        "default": [1, 1, 1],
        "minItems": 3,
        "maxItems": 3
      },
      "roughness": {
        "description": "The roughness of the specular reflection. Lower numbers produce sharper reflections, higher numbers produce blurrier reflections.",
        "type": "number",
        "default": 0.5
      },
      "ior": {
        "description": "Index of refraction of a dielectric material. Does not apply to metals (conductors).",
        "type": "number",
        "default": 1.5
      },
      "subsurfaceRadius": {
        "description": "The approximate distance up to which light can scatter below the surface, also known as “mean free path” (MFP). Specified in centimeters.",
        "type": "array",
        "items": {
          "type": "number"
        },
        "default": [1, 1, 1],
        "minItems": 3,
        "maxItems": 3
      },
      "transmission": {
        "description": "",
        "type": "number",
        "default": 0
      },
      "transmissionDepth": {
        "description": "Controls the depth into the volume at which the Transmission Color is realized.",
        "type": "number",
        "default": 0
      },
      "transmissionDispersion": {
        "description": "Abbe number, describing how much the index of refraction varies across wavelengths. For glass and diamonds, this is typically in the range of 10 to 70, with lower numbers giving more dispersion.",
        "type": "number",
        "default": 0
      },
      "complexIor": {
        "description": "Complex IOR values, n (refractive index), and k (extinction coefficient), for each color channel, in the following order: nR, kR, nG, kG, nB, kB. Calculated from spectral IOR data files with script from https://github.com/natyh/material-params",
        "type": "array",
        "items": {
          "type": "number"
        },
        "default": [0, 0, 0, 0, 0, 0],
        "minItems": 6,
        "maxItems": 6
      },
      "thinFilmThickness": {
        "description": "The thickness of the thin film layer on the base (in nanometers).",
        "type": "number",
        "default": 0
      },
      "thinFilmIor": {
        "description": "The index of refraction of the thin-film.",
        "type": "number",
        "default": 1.5
      },
      "density": {
        "description": "Density measured in kg/m3.",
        "type": "number",
        "default": 1000
      },
      "densityRange": {
        "description": "The typical range of density.",
        "type": "array",
        "items": {
          "type": "number"
        },
        "default": [1000, 1000],
        "minItems": 2,
        "maxItems": 2
      },
      "viscosity": {
        "description": "Dynamic viscosity measured in millipascal-seconds (mPa⋅s) at a temperature of 20°C. 1 mPa⋅s (millipascal-second) = 1 cP (centipoise). Used for fluid simulations.",
        "type": "number",
        "default": 1
      },
      "surfaceTension": {
        "description": "Surface tension measured in millinewton per meter (mN/m) at a temperature of 20°C. 1 mN/m = 1 dyn/cm.",
        "type": "number",
        "default": 1
      },
      "acousticAbsorption": {
        "description": "Absorption coefficients at 125, 250, 500, 1000, 2000, and 4000 kHz.",
        "type": "array",
        "items": {
          "type": "number"
        },
        "default": [0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
        "minItems": 6,
        "maxItems": 6
      },
      "category": {
        "type": "array",
        "items": {
          "enum": [
            "Calibration",
            "Crystal",
            "Gas",
            "Human",
            "Liquid",
            "Manmade",
            "Metal",
            "Organic",
            "Plastic"
          ]
        },
        "minItems": 1,
        "maxItems": 1
      },
      "group": {
        "description": "Can be used to group similar materials together. For example, Skin I, Skin II, and Skin III would be part of the same group: Skin.",
        "type": "string",
        "default": "Group"
      },
      "description": {
        "description": "This field should be used for disclaimers and other useful info for CG artists that may affect the way they use the values. It's totally fine to leave this empty.",
        "type": "string",
        "maxLength": 500
      },
      "sources": {
        "description": "Provide at least one source for the values.",
        "type": "array",
        "items": {
          "type": "string",
          "minLength": 1
        },
        "minItems": 1,
        "uniqueItems": true
      },
      "tags": {
        "description": "Tags for when there are alternative names or spellings of the same material.",
        "type": "array",
        "items": {
          "type": "string"
        },
        "uniqueItems": true
      },
      "reference": {
        "description": "Links to reference images.",
        "type": "array",
        "items": {
          "type": "string",
          "minLength": 1
        },
        "uniqueItems": true
      }
    },
    "required": [
      "name",
      "color",
      "metalness",
      "roughness",
      "ior",
      "density",
      "category",
      "description",
      "sources",
      "reference"
    ]
  }
}

=== AntonPalmqvist/physically-based-api/deploy/materials.json
[
  {
    "name": "Aluminum",
    "color": [0.916, 0.923, 0.924],
    "metalness": 1,
    "specularColor": [0.989, 0.989, 0.972],
    "roughness": 0,
    "ior": 1.5,
    "complexIor": [0.728978, 6.45971, 0.588215, 5.19646, 0.78354, 4.37746],
    "density": 2700,
    "category": ["Metal"],
    "description": "",
    "sources": [
      "https://refractiveindex.info/?shelf=main&book=Al&page=Cheng",
      "https://arxiv.org/pdf/2512.23696#appendix.D",
      "https://en.wikipedia.org/wiki/Aluminium",
      "https://en.wikipedia.org/wiki/Density",
      "https://en.wikipedia.org/wiki/Mirror"
    ],
    "tags": ["aluminium", "mirror"],
    "reference": [
      "https://raw.githubusercontent.com/AntonPalmqvist/physically-based-api/main/images/renders/cycles/600/aluminum.jpeg"
    ]
  },
  {
    "name": "Banana",
    "color": [0.634, 0.532, 0.111],
    "metalness": 0,
    "roughness": 0.5,
    "ior": 1.5,
    "density": 0,
    "category": ["Organic"],
    "description": "",
    "sources": ["https://spectraldb.com/measurements/00379/"],
    "tags": [""],
    "reference": [
      "https://raw.githubusercontent.com/AntonPalmqvist/physically-based-api/main/images/renders/cycles/600/banana.jpeg"
    ]
  },
  {
    "name": "Beryllium",
    "color": [0.539, 0.533, 0.534],
    "metalness": 1,
    "specularColor": [0.549, 0.503, 0.364],
    "roughness": 0,
    "ior": 1.5,
    "complexIor": [3.21038, 3.29815, 3.32907, 3.11669, 3.77105, 2.66995],
    "density": 1850,
    "category": ["Metal"],
    "description": "",
    "sources": [
      "https://refractiveindex.info/?shelf=main&book=Be&page=Rakic-BB",
      "https://arxiv.org/pdf/2512.23696#appendix.D",
      "https://en.wikipedia.org/w/index.php?title=Beryllium&oldid=1295895956",
      "https://en.wikipedia.org/wiki/Density"
    ],
    "tags": [""],
    "reference": [
      "https://raw.githubusercontent.com/AntonPalmqvist/physically-based-api/main/images/renders/cycles/600/beryllium.jpeg"
    ]
  },
  {
    "name": "Blackboard",
    "color": [0.039, 0.039, 0.039],
    "metalness": 0,
    "roughness": 0.9,
    "ior": 1.5,
    "density": 0,
    "category": ["Manmade"],
    "description": "",
    "sources": [
      "https://spectraldb.com/measurements/00079/",
      "https://github.com/AntonPalmqvist/physically-based-api/tree/main/data/materials/blackboard/"
    ],
    "tags": [""],
    "reference": [
      "https://raw.githubusercontent.com/AntonPalmqvist/physically-based-api/main/images/renders/cycles/600/blackboard.jpeg"
    ]
  },
  {
    "name": "Blood",
    "color": [0.64448, 0.003, 0.005],
    "metalness": 0,
    "roughness": 0,
    "ior": 1.35,
    "transmission": 1,
    "transmissionDepth": 0.08,
    "transmissionDispersion": 54,
    "density": 1060,
    "viscosity": 2.8,
    "surfaceTension": 56,
    "category": ["Human"],
    "description": "The color of blood depends on its oxygen level. When there is plenty of oxygen, the color is a brighter red. The reason is because of a protein called hemoglobin, which carries the oxygen in your blood. When hemoglobin has a full oxygen load, it has a bright red color, and when it's deoxygenated it's a darker red. For example, arterial and capillary blood is bright, and venous blood is dark.",
    "sources": [
      "https://en.wikipedia.org/wiki/Blood",
      "https://en.wikipedia.org/wiki/Blood_red",
      "https://refractiveindex.info/?shelf=other&book=blood&page=Liu",
      "https://hypertextbook.com/facts/2004/MichaelShmukler.shtml",
      "https://www.researchgate.net/figure/Color-chart-for-the-measurement-of-methemoglobin-The-color-chart-was-prepared-according_fig2_26884296",
      "https://www.engineeringtoolbox.com/absolute-viscosity-liquids-d_1259.html",
      "https://en.wikipedia.org/wiki/Hemorheology",
      "https://www.frontiersin.org/articles/10.3389/fphys.2019.01329/full",
      "https://nextlimitsupport.atlassian.net/wiki/spaces/rf2016docs/pages/5497120/Hybrido+Viscosity+Table",
      "https://wiki.anton-paar.com/en/whole-blood/",
      "https://en.wikipedia.org/w/index.php?title=Surface_tension&oldid=1304099149#Values"
    ],
    "tags": ["liquid"],
    "reference": [
      "https://raw.githubusercontent.com/AntonPalmqvist/physically-based-api/main/images/renders/cycles/600/blood.jpeg"
    ]
  },
  {
    "name": "Bone",
    "color": [0.793, 0.793, 0.664],
    "metalness": 0,
    "roughness": 0.9,
    "ior": 1.5,
    "density": 1900,
    "densityRange": [1000, 2000],
    "category": ["Organic"],
    "description": "",
    "sources": [
      "https://hypertextbook.com/facts/2002/AnnaYarusskaya.shtml",
      "https://www.tandfonline.com/doi/pdf/10.3109/02841867809127938",
      "https://en.wikipedia.org/wiki/Bone"
    ],
    "tags": ["skeleton"],
    "reference": [
      "https://raw.githubusercontent.com/AntonPalmqvist/physically-based-api/main/images/renders/cycles/600/bone.jpeg"
    ]
  },
  {
    "name": "Brass",
    "color": [0.91, 0.778, 0.423],
    "metalness": 1,
    "specularColor": [0.995, 0.974, 0.747],
    "roughness": 0,
    "ior": 1.5,
    "complexIor": [0.341048, 4.14088, 0.53349, 2.67993, 1.42749, 1.87543],
    "density": 8600,
    "category": ["Metal"],
    "description": "Brass is an alloy of copper and zinc, with a bright and gold-like appearance. It is similar to bronze, another alloy containing copper that uses tin instead of zinc. Historically, the distinction between the two alloys has been less consistent and clear, and modern practice in museums and archaeology increasingly avoids both terms for historical objects in favor of the more general \"copper alloy\".",
    "sources": [
      "https://refractiveindex.info/?shelf=3d&book=metals&page=brass",
      "https://arxiv.org/pdf/2512.23696#appendix.D",
      "https://en.wikipedia.org/wiki/Brass",
      "https://en.wikipedia.org/wiki/Density"
    ],
    "tags": [""],
    "reference": [
      "https://raw.githubusercontent.com/AntonPalmqvist/physically-based-api/main/images/renders/cycles/600/brass.jpeg"
    ]
  },
  {
    "name": "Brick",
    "color": [0.262, 0.095, 0.061],
    "metalness": 0,
    "roughness": 0.9,
    "ior": 1.5,
    "density": 2000,
    "densityRange": [500, 2400],
    "acousticAbsorption": [0.03, 0.03, 0.03, 0.04, 0.05, 0.07],
    "category": ["Manmade"],
    "description": "",
    "sources": [
      "https://github.com/AntonPalmqvist/physically-based-api/tree/main/data/materials/brick/",
      "https://en.wikipedia.org/wiki/Brick",
      "https://www.acoustic-supplies.com/absorption-coefficient-chart/",
      "https://en.wikipedia.org/wiki/Absorption_(acoustics)",
      "https://www.acoustic.ua/st/web_absorption_data_eng.pdf"
    ],
    "tags": [""],
    "reference": [
      "https://raw.githubusercontent.com/AntonPalmqvist/physically-based-api/main/images/renders/cycles/600/brick.jpeg"
    ]
  },
  {
    "name": "Car Paint",
    "color": [0.1, 0.1, 0.1],
    "metalness": 0,
    "roughness": 0,
    "ior": 1.5,
    "density": 0,
    "category": ["Manmade"],
    "description": "Modern car paints are nearly always an acrylic polyurethane \"enamel\" with a pigmented basecoat and a clear topcoat. It may be described as \"acrylic\", \"acrylic enamel\", \"urethane\", etc. and the clearcoat in particular may be described as a lacquer. The size of the metal flakes in metallic paints is typically between 100 to 400 microns in diameter. Modern automobile paint is applied in several layers, with a total thickness of around 100 μm (0.1mm).",
    "sources": [
      "https://en.wikipedia.org/wiki/Automotive_paint",
      "https://en.wikipedia.org/wiki/Lacquer#Acrylic_lacquers",
      "https://hal.science/hal-04030017/document",
      "https://patentscope.wipo.int/search/en/detail.jsf?docId=WO2011163461",
      "https://thecandeshop.com/metal-flake-for-cars/",
      "https://www.theultimatefinish.co.uk/car-care-blog/featured/paintwork/"
    ],
    "tags": ["acrylic", "coat", "car paint", "lacquer"],
    "reference": [
      "https://raw.githubusercontent.com/AntonPalmqvist/physically-based-api/main/images/renders/cycles/600/car-paint.jpeg"
    ]
  },
  {
    "name": "Carrot",
    "color": [0.713, 0.17, 0.026],
    "metalness": 0,
    "roughness": 0.5,
    "ior": 1.5,
    "density": 0,
    "category": ["Organic"],
    "description": "",
    "sources": ["https://spectraldb.com/measurements/00456/"],
    "tags": [""],
    "reference": [
      "https://raw.githubusercontent.com/AntonPalmqvist/physically-based-api/main/images/renders/cycles/600/carrot.jpeg"
    ]
  },
  {
    "name": "Cesium",
    "color": [0.718, 0.554, 0.237],
    "metalness": 1,
    "specularColor": [0.997, 1.002, 1.073],
    "roughness": 0,
    "ior": 1.5,
    "complexIor": [0.204334, 1.19256, 0.272018, 0.906033, 0.449252, 0.517209],
    "density": 1886,
    "category": ["Metal"],
    "description": "",
    "sources": [
      "https://refractiveindex.info/?shelf=main&book=Cs&page=Monin",
      "https://arxiv.org/pdf/2512.23696#appendix.D",
      "https://en.wikipedia.org/w/index.php?title=Caesium&oldid=1297091310"
    ],
    "tags": ["caesium"],
    "reference": [
      "https://raw.githubusercontent.com/AntonPalmqvist/physically-based-api/main/images/renders/cycles/600/cesium.jpeg"
    ]
  },
  {
    "name": "Charcoal",
    "color": [0.02, 0.02, 0.02],
    "metalness": 0,
    "roughness": 0.9,
    "ior": 1.5,
    "density": 300,
    "densityRange": [200, 500],
    "category": ["Organic"],
    "description": "",
    "sources": [
      "https://chrisbrejon.com/articles/albedo-and-pointers-gamut/",
      "https://seblagarde.wordpress.com/2011/08/17/feeding-a-physical-based-lighting-mode/",
      "http://ukrfuel.com/news-physical-properties-of-charcoal-22.html",
      "https://en.wikipedia.org/wiki/Activated_carbon"
    ],
    "tags": [""],
    "reference": [
      "https://raw.githubusercontent.com/AntonPalmqvist/physically-based-api/main/images/renders/cycles/600/charcoal.jpeg"
    ]
  },
  {
    "name": "Chocolate",
    "color": [0.162, 0.091, 0.06],
    "metalness": 0,
