=== AntonPalmqvist/physically-based-api/schemas/schema-lightsources.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Light",
  "description": "A light source.",
  "type": "array",
  "items": {
    "additionalProperties": false,
    "properties": {
      "name": {
        "description": "Name of the light source.",
        "type": "string",
        "default": "Name"
      },
      "color": {
        "description": "Color of the light source.",
        "type": "array",
        "items": {
          "type": "number"
        },
        "default": [1, 1, 1],
        "minItems": 3,
        "maxItems": 3
      },
      "temperature": {
        "description": "Color temperature in Kelvin, if color lies on the Planckian curve.",
        "type": "number",
        "default": 6500
      },
      "temperatureRange": {
        "description": "The typical range of color temperature for this specific light source.",
        "type": "array",
        "items": {
          "type": "number"
        },
        "default": [6500, 7000],
        "minItems": 2,
        "maxItems": 2
      },
      "intensity": {
        "type": "number",
        "default": 0
      },
      "intensityRange": {
        "description": "The typical range of intensity for this specific light source.",
        "type": "array",
        "items": {
          "type": "number"
        },
        "default": [0, 1],
        "minItems": 2,
        "maxItems": 2
      },
      "unit": {
        "type": "array",
        "items": {
          "enum": ["lm", "lx", "cd/m2"]
        },
        "minItems": 1,
        "maxItems": 1
      },
      "angle": {
        "description": "The maximum beam angle in degrees. For a directional light, this specifies angular diameter instead.",
        "type": "number",
        "default": 90
      },
      "sourceSize": {
        "description": "The size of the light source in centimeters. [Radius] if point or spot. [Width, Height] if surface. [Length, Radius] if cylinder.",
        "type": "array",
        "items": {
          "type": "number"
        },
        "minItems": 1,
        "maxItems": 2
      },
      "type": {
        "description": "The type of light, for DCC applications.",
        "type": "array",
        "items": {
          "enum": [
            "directional",
            "surface",
            "spot",
            "point",
            "cylinder",
            "dome"
          ]
        },
        "minItems": 1,
        "maxItems": 1
      },
      "variants": {
        "description": "If the light source comes in different variations, they can be described here.",
        "type": "array",
        "minItems": 1,
        "items": {
          "additionalProperties": false,
          "type": "object",
          "properties": {
            "format": {
              "description": "Specifies the format.",
              "type": "string",
              "default": "Default"
            },
            "color": {
              "description": "Color of the light source.",
              "type": "array",
              "items": {
                "type": "number"
              },
              "default": [1, 1, 1],
              "minItems": 3,
              "maxItems": 3
            },
            "temperature": {
              "description": "Color temperature in Kelvin, if color lies on the Planckian curve.",
              "type": "number",
              "default": 6500
            },
            "intensity": {
              "description": "Intensity of the light emitted from the light source.",
              "type": "number",
              "default": 0
            },
            "angle": {
              "description": "The maximum beam angle in degrees. For a directional light, this specifies angular diameter instead.",
              "type": "number",
              "default": 90
            },
            "sourceSize": {
              "description": "The size of the light source in centimeters. [Radius] if point or spot. [Width, Height] if surface. [Length, Radius] if cylinder.",
              "type": "array",
              "items": {
                "type": "number"
              },
              "minItems": 1,
              "maxItems": 2
            }
          }
        },
        "required": ["format", "color", "intensity"]
      },
      "category": {
        "type": "array",
        "items": {
          "enum": ["Artificial", "Natural"]
        },
        "minItems": 1,
        "maxItems": 1
      },
      "description": {
        "description": "This field should be used for disclaimers and other useful info for CG artists that may affect the way they use the values. It's totally fine to leave this empty.",
        "type": "string",
        "maxLength": 500
      },
      "sources": {
        "description": "Provide at least one source for the values.",
        "type": "array",
        "items": {
          "type": "string",
          "minLength": 1
        },
        "minItems": 1,
        "uniqueItems": true
      },
      "tags": {
        "description": "Tags",
        "type": "array",
        "items": {
          "type": "string"
        },
        "uniqueItems": true
      }
    },
    "anyOf": [
      {
        "required": ["color", "intensity"]
      },
      {
        "required": ["variants"]
      }
    ],
    "required": [
      "name",
      "color",
      "intensity",
      "unit",
      "category",
      "description",
      "sources"
    ]
  }
}

=== AntonPalmqvist/physically-based-api/deploy/lightsources.json
[
  {
    "name": "Aputure amaran 300c",
    "color": [1.0, 0.859, 0.778],
    "temperature": 5600,
    "temperatureRange": [2500, 7500],
    "intensity": 19389,
    "sourceSize": [4],
    "variants": [
      {
        "format": "Bare Bulb",
        "color": [1.0, 0.859, 0.778],
        "temperature": 5600,
        "angle": 89.6,
        "intensity": 17244
      },
      {
        "format": "Hyper Reflector",
        "color": [1.0, 0.859, 0.778],
        "temperature": 5600,
        "angle": 64.8,
        "intensity": 26155
      }
    ],
    "unit": ["lm"],
    "angle": 90,
    "type": ["spot"],
    "category": ["Artificial"],
    "description": "",
    "sources": [
      "https://help.aputure.com/en/amaran-150c-300c/photometrics-technical-specifications",
      "https://docs.aputure.com/hubfs/Knowledge%20Base/amaran/150c-300c/All%20Files/amaran%20300c%20Product%20Manual%20.pdf?_gl=1*53mffx*_gcl_au*MTAzNTY3Nzg5Ny4xNzAzNzk4MTc1"
    ]
  },
  {
    "name": "Aputure amaran P60c",
    "color": [0.828, 0.841, 1.0],
    "temperature": 7500,
    "temperatureRange": [2500, 7500],
    "intensity": 3000,
    "unit": ["lm"],
    "angle": 45,
    "sourceSize": [27, 21],
    "type": ["surface"],
    "category": ["Artificial"],
    "description": "",
    "sources": [
      "https://help.aputure.com/en/amaran-p60c-p60x/overview-of-p60c-p60x",
      "https://docs.aputure.com/hubfs/Knowledge%20Base/amaran/p60x%20and%20p60c/All%20files/amaran-P60c-Product-Manual-EN_211211-.pdf",
      "https://help.aputure.com/en/amaran-p60c-p60x/photometrics-and-technical-specifications"
    ]
  },
  {
    "name": "Aputure STORM 1000c",
    "color": [1.0, 0.859, 0.778],
    "temperature": 5600,
    "temperatureRange": [1800, 20000],
    "intensity": 600000,
    "sourceSize": [4],
    "variants": [
      {
        "format": "No Reflector",
        "color": [1.0, 0.859, 0.778],
        "temperature": 5600,
        "angle": 65,
        "intensity": 61250
      },
      {
        "format": "15º Reflector",
        "color": [1.0, 0.859, 0.778],
        "temperature": 5600,
        "angle": 15,
        "intensity": 600000
      },
      {
        "format": "30º Reflector",
        "color": [1.0, 0.859, 0.778],
        "temperature": 5600,
        "angle": 30,
        "intensity": 250000
      },
      {
        "format": "45º Reflector",
        "color": [1.0, 0.859, 0.778],
        "temperature": 5600,
        "angle": 45,
        "intensity": 125000
      }
    ],
    "unit": ["lx"],
    "type": ["spot"],
    "category": ["Artificial"],
    "description": "",
    "sources": ["https://aputure.com/products/storm-1000c"]
  },
  {
    "name": "Aputure STORM 1200x",
    "color": [1.0, 0.859, 0.778],
    "temperature": 5600,
    "temperatureRange": [2500, 10000],
    "sourceSize": [4],
    "intensity": 202500,
    "variants": [
      {
        "format": "No Reflector",
        "color": [1.0, 0.859, 0.778],
        "temperature": 5600,
        "angle": 70,
        "intensity": 76400
      },
      {
        "format": "15º Reflector",
        "color": [1.0, 0.859, 0.778],
        "temperature": 5600,
        "angle": 15,
        "intensity": 864900
      },
      {
        "format": "30º Reflector",
        "color": [1.0, 0.859, 0.778],
        "temperature": 5600,
        "angle": 30,
        "intensity": 376200
      },
      {
        "format": "45º Reflector",
        "color": [1.0, 0.859, 0.778],
        "temperature": 5600,
        "angle": 45,
        "intensity": 202500
      }
    ],
    "unit": ["lx"],
    "type": ["spot"],
    "category": ["Artificial"],
    "description": "",
    "sources": [
      "https://aputure.com/EN-US/products/storm-1200x",
      "https://24055135.fs1.hubspotusercontent-na1.net/hubfs/24055135/Aputure_Storm_1200x_One_Sheet_2024-09-09a.pdf"
    ]
  },
  {
    "name": "Arri M-Series M8",
    "color": [1.0, 0.899, 0.875],
    "temperature": 6000,
    "intensity": 41300,
    "variants": [
      {
        "format": "Flood",
        "angle": 60,
        "intensity": 41300
      },
      {
        "format": "Medium",
        "angle": 40,
        "intensity": 76100
      },
      {
        "format": "Spot",
        "angle": 15,
        "intensity": 405000
      }
    ],
    "sourceSize": [11.5],
    "unit": ["lx"],
    "type": ["spot"],
    "category": ["Artificial"],
    "description": "",
    "sources": [
      "https://www.arri.com/en/lighting/daylight/m-series/m8",
      "https://www.arri.com/resource/blob/31482/8764688fa9ce88b33bf3f4f48e2fb52a/arri-m-series-m8-data-sheet-en-sep2018-data.pdf"
    ]
  },
  {
    "name": "Arri SkyPanel S60 Pro",
    "color": [1.0, 0.859, 0.778],
    "temperature": 5600,
    "temperatureRange": [2800, 10000],
    "intensity": 41100,
    "sourceSize": [64.5, 30.0],
    "angle": 103,
    "unit": ["lm"],
    "type": ["surface"],
    "category": ["Artificial"],
    "description": "",
    "sources": [
      "https://www.arri.com/en/lighting/led-panel-lights/skypanel-pro/tech-data",
      "https://www.arri.com/resource/blob/384436/68055e513496ca273128f1741cc04f92/arri-s60-pro-data-sheet-en-data.pdf"
    ]
  },
  {
    "name": "Arri SkyPanel X",
    "color": [1.0, 0.859, 0.778],
    "temperature": 5600,
    "temperatureRange": [1500, 20000],
    "intensity": 48000,
    "variants": [
      {
        "format": "Open-Face",
        "color": [1.0, 0.859, 0.778],
        "temperature": 5600,
        "angle": 121,
        "intensity": 48000
      },
      {
        "format": "Dome",
        "color": [1.0, 0.859, 0.778],
        "temperature": 5600,
        "angle": 107,
        "intensity": 42700
      },
      {
        "format": "S60 Adapter",
        "color": [1.0, 0.859, 0.778],
        "temperature": 5600,
        "angle": 101,
        "intensity": 35400
      },
      {
        "format": "HyPer Optic",
        "color": [1.0, 0.859, 0.778],
        "temperature": 5600,
        "angle": 11,
        "intensity": 22000
      }
    ],
    "sourceSize": [64.8, 30.3],
    "unit": ["lm"],
    "type": ["surface"],
    "category": ["Artificial"],
    "description": "",
    "sources": [
      "https://www.arri.com/en/lighting/led-panel-lights/skypanel-x/tech-data",
      "https://www.arri.com/resource/blob/341262/e55242c6535912778f7f39d38f490c90/arri-skypanel-x-data-sheet-en-data.pdf"
    ]
  },
  {
    "name": "Candle Flame",
    "color": [1.0, 0.22, 0.0],
    "temperature": 1850,
    "intensity": 13,
    "unit": ["lm"],
    "sourceSize": [1],
    "type": ["point"],
    "category": ["Natural"],
    "description": "",
    "sources": [
      "https://en.wikipedia.org/wiki/Candle#Characteristics",
      "https://en.wikipedia.org/wiki/Color_temperature"
    ]
  },
  {
    "name": "Car Headlight (Halogen)",
    "color": [1.0, 0.571, 0.259],
    "temperature": 3500,
    "intensity": 1500,
    "intensityRange": [1000, 2000],
    "sourceSize": [5],
    "angle": 15,
    "unit": ["lm"],
    "type": ["spot"],
    "category": ["Artificial"],
    "description": "Tungsten-halogen bulbs, commonly just called halogen, are the most widely used bulbs in car headlights. High beam is approximately double the intensity of a low beam.",
    "sources": [
      "https://www.bulbfacts.com/halogen-bulbs/chart/",
      "https://en.wikipedia.org/wiki/Headlamp#Light_sources",
      "https://www.onallcylinders.com/2015/02/27/light-source-quick-guide-automotive-lighting/"
    ]
  },
  {
    "name": "Car Headlight (LED)",
    "color": [1.0, 0.792, 0.628],
    "temperature": 3500,
    "temperatureRange": [5000, 6000],
    "intensity": 3000,
    "intensityRange": [2000, 5000],
    "sourceSize": [5],
    "angle": 15,
    "unit": ["lm"],
    "type": ["spot"],
    "category": ["Artificial"],
    "description": "",
    "sources": [
      "https://www.bulbfacts.com/led-kits/chart/",
      "https://en.wikipedia.org/w/index.php?title=Headlamp&oldid=1274156171#Light_sources",
      "https://www.onallcylinders.com/2015/02/27/light-source-quick-guide-automotive-lighting/"
    ]
  },
  {
    "name": "Digital Display",
    "color": [1.0, 0.943, 0.992],
    "temperature": 6500,
    "intensity": 200,
    "intensityRange": [100, 2500],
    "unit": ["cd/m2"],
    "sourceSize": [61, 38],
    "type": ["surface"],
    "category": ["Artificial"],
    "description": "Displays like computer monitors, TVs, signage, etc. Typically they have a temperature of 6500K but it can vary. The sRGB spec for monitors targets 80 cd/m2. Typically, monitors calibrated for broadcast or studio color grading should have a brightness of 100 cd/m2 in Japan and in the United States, or 120 cd/m2 in the European Union. This is however considered quite dark for normal use, so consumer monitors tend to be brighter.",
    "sources": [
      "https://en.wikipedia.org/wiki/Color_temperature",
      "https://en.wikipedia.org/wiki/Candela_per_square_metre"
    ],
    "tags": ["computer", "monitor", "lcd", "oled", "screen"]
  },
  {
    "name": "Firefly",
    "color": [1, 1, 1],
    "temperature": 0,
    "intensity": 0.0006,
    "variants": [
      {
        "format": "Green",
        "color": [0, 1, 0],
        "intensity": 0.0006
      },
      {
        "format": "Yellow",
        "color": [1.0, 0.5, 0],
        "intensity": 0.0006
      },
      {
        "format": "Red",
        "color": [1.0, 0, 0],
        "intensity": 0.0006
      }
    ],
    "unit": ["lm"],
    "sourceSize": [0.25],
    "type": ["point"],
    "category": ["Natural"],
    "description": "Fireflies produce a \"cold light\", with no infrared or ultraviolet frequencies. The light may be yellow, green, or pale red, with wavelengths from 510 to 670 nanometers. Some species such as the dimly glowing \"blue ghost\" of the Eastern US may seem to emit blueish-white light from a distance and in low light conditions, but their glow is bright green when observed up close. Their perceived blue tint may be due to the Purkinje effect.",
    "sources": [
      "https://www.nature.com/articles/s41598-021-91839-3",
